services:
  privateer:
    restart: unless-stopped
    image: privateer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5901:5901/tcp" # Make sure this is only localhost

